on: [push]

jobs:
    deploy_job:
      runs-on: ubuntu-latest
      name: deploy
      if: github.ref == 'refs/head/master'
      steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: deploy file
            uses: wlixcc/SFTP-Deploy-Action@v1.2.4
            with:
              username: 'robynfhveitch'
              server: 'robynveitch.com'
              ssh_private_key: ${{ secrets.SSHKEY }} 
              local_path: './*'
              remote_path: '/var/www/html/robynveitch/wp-content/themes/robynveitch'
              sftpArgs: '-o ConnectTimeout=5'
